// This file is @generated by prost-build.
/// / Message header key-value pair
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Header {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// / Request to publish a single message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishRequest {
    /// / Unique identifier for idempotency - if not provided, one will be generated
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Type of aggregate/entity this message relates to
    #[prost(string, tag = "2")]
    pub aggregate_type: ::prost::alloc::string::String,
    /// / Unique identifier of the aggregate
    #[prost(string, tag = "3")]
    pub aggregate_id: ::prost::alloc::string::String,
    /// / Type/name of the event
    #[prost(string, tag = "4")]
    pub event_type: ::prost::alloc::string::String,
    /// / JSON-encoded message payload
    #[prost(bytes = "vec", tag = "5")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// / Optional headers for Kafka message
    #[prost(message, repeated, tag = "6")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
    /// / Target Kafka topic
    #[prost(string, tag = "7")]
    pub topic: ::prost::alloc::string::String,
    /// / Optional partition key for Kafka partitioning
    #[prost(string, tag = "8")]
    pub partition_key: ::prost::alloc::string::String,
    /// / Override default retry configuration
    #[prost(message, optional, tag = "9")]
    pub retry_config: ::core::option::Option<RetryConfig>,
    /// / Request metadata
    #[prost(message, optional, tag = "10")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response for publish request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishResponse {
    /// / Unique message identifier
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Current status of the message
    #[prost(enumeration = "MessageStatus", tag = "2")]
    pub status: i32,
    /// / Whether this was a duplicate request
    #[prost(bool, tag = "3")]
    pub duplicate: bool,
    /// / Timestamp when message was accepted
    #[prost(int64, tag = "4")]
    pub accepted_at: i64,
    /// / Error message if request failed
    #[prost(string, tag = "5")]
    pub error: ::prost::alloc::string::String,
}
/// / Request to publish multiple messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishBatchRequest {
    /// / List of messages to publish
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<PublishRequest>,
    /// / Request metadata
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response for batch publish request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishBatchResponse {
    /// / Individual responses for each message
    #[prost(message, repeated, tag = "1")]
    pub responses: ::prost::alloc::vec::Vec<PublishResponse>,
    /// / Number of successfully accepted messages
    #[prost(int32, tag = "2")]
    pub success_count: i32,
    /// / Number of failed messages
    #[prost(int32, tag = "3")]
    pub failure_count: i32,
}
/// / Request to get message status
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessageStatusRequest {
    /// / Message ID to query
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Request metadata
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response with message status
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessageStatusResponse {
    /// / Message ID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Current status
    #[prost(enumeration = "MessageStatus", tag = "2")]
    pub status: i32,
    /// / Number of retry attempts made
    #[prost(int32, tag = "3")]
    pub retry_count: i32,
    /// / Timestamp of last status change
    #[prost(int64, tag = "4")]
    pub last_updated: i64,
    /// / Error message if failed
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
    /// / Timestamp when published to Kafka
    #[prost(int64, tag = "6")]
    pub published_at: i64,
    /// / Topic the message was published to
    #[prost(string, tag = "7")]
    pub topic: ::prost::alloc::string::String,
}
/// / Request to cancel a pending message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelMessageRequest {
    /// / Message ID to cancel
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Request metadata
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response for cancel request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelMessageResponse {
    /// / Whether cancellation was successful
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// / Current status of the message
    #[prost(enumeration = "MessageStatus", tag = "2")]
    pub status: i32,
    /// / Error message if cancellation failed
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// / Request to register a subscriber
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterSubscriberRequest {
    /// / Unique identifier for this subscriber
    #[prost(string, tag = "1")]
    pub subscriber_id: ::prost::alloc::string::String,
    /// / Human-readable service name
    #[prost(string, tag = "2")]
    pub service_name: ::prost::alloc::string::String,
    /// / gRPC endpoint to call for message delivery
    #[prost(string, tag = "3")]
    pub grpc_endpoint: ::prost::alloc::string::String,
    /// / Topic patterns to subscribe to - supports wildcards
    /// / Examples: "orders.*", "payments.created", "events.>"
    #[prost(string, repeated, tag = "4")]
    pub topic_patterns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// / Optional delivery configuration
    #[prost(message, optional, tag = "5")]
    pub delivery_config: ::core::option::Option<DeliveryConfig>,
    /// / Request metadata
    #[prost(message, optional, tag = "6")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response for subscriber registration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterSubscriberResponse {
    /// / Subscriber ID
    #[prost(string, tag = "1")]
    pub subscriber_id: ::prost::alloc::string::String,
    /// / Whether registration was successful
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// / Error message if registration failed
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// / Request to unregister a subscriber
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterSubscriberRequest {
    /// / Subscriber ID to unregister
    #[prost(string, tag = "1")]
    pub subscriber_id: ::prost::alloc::string::String,
    /// / Request metadata
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response for unregistration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterSubscriberResponse {
    /// / Whether unregistration was successful
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// / Error message if unregistration failed
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// / Request to update subscriber configuration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateSubscriberRequest {
    /// / Subscriber ID to update
    #[prost(string, tag = "1")]
    pub subscriber_id: ::prost::alloc::string::String,
    /// / New gRPC endpoint
    #[prost(string, tag = "2")]
    pub grpc_endpoint: ::prost::alloc::string::String,
    /// / New topic patterns
    #[prost(string, repeated, tag = "3")]
    pub topic_patterns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// / Whether subscriber is active
    #[prost(bool, tag = "4")]
    pub active: bool,
    /// / New delivery configuration
    #[prost(message, optional, tag = "5")]
    pub delivery_config: ::core::option::Option<DeliveryConfig>,
    /// / Request metadata
    #[prost(message, optional, tag = "6")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response for update request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateSubscriberResponse {
    /// / Whether update was successful
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// / Error message if update failed
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// / Request to list subscribers
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSubscribersRequest {
    /// / Filter by topic pattern
    #[prost(string, tag = "1")]
    pub topic_filter: ::prost::alloc::string::String,
    /// / Filter by active status
    #[prost(bool, tag = "2")]
    pub active_only: bool,
    /// / Request metadata
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response with subscriber list
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSubscribersResponse {
    /// / List of subscribers
    #[prost(message, repeated, tag = "1")]
    pub subscribers: ::prost::alloc::vec::Vec<SubscriberInfo>,
}
/// / Information about a subscriber
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscriberInfo {
    /// / Subscriber ID
    #[prost(string, tag = "1")]
    pub subscriber_id: ::prost::alloc::string::String,
    /// / Service name
    #[prost(string, tag = "2")]
    pub service_name: ::prost::alloc::string::String,
    /// / gRPC endpoint
    #[prost(string, tag = "3")]
    pub grpc_endpoint: ::prost::alloc::string::String,
    /// / Subscribed topic patterns
    #[prost(string, repeated, tag = "4")]
    pub topic_patterns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// / Whether subscriber is active
    #[prost(bool, tag = "5")]
    pub active: bool,
    /// / Timestamp when registered
    #[prost(int64, tag = "6")]
    pub registered_at: i64,
}
/// / Request to subscribe to event stream
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeEventsRequest {
    /// / Subscriber ID - must be registered
    #[prost(string, tag = "1")]
    pub subscriber_id: ::prost::alloc::string::String,
    /// / Topic patterns to receive
    #[prost(string, repeated, tag = "2")]
    pub topic_patterns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// / Start from beginning or latest
    #[prost(enumeration = "SubscriptionPosition", tag = "3")]
    pub position: i32,
    /// / Request metadata
    #[prost(message, optional, tag = "4")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Event delivered to subscriber
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeliverEvent {
    /// / Unique message ID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Topic the message was received from
    #[prost(string, tag = "2")]
    pub topic: ::prost::alloc::string::String,
    /// / Partition number
    #[prost(int32, tag = "3")]
    pub partition: i32,
    /// / Offset in partition
    #[prost(int64, tag = "4")]
    pub offset: i64,
    /// / Message key
    #[prost(string, tag = "5")]
    pub key: ::prost::alloc::string::String,
    /// / Message payload
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// / Message headers
    #[prost(message, repeated, tag = "7")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
    /// / Timestamp when message was produced
    #[prost(int64, tag = "8")]
    pub timestamp: i64,
    /// / Event type for routing
    #[prost(string, tag = "9")]
    pub event_type: ::prost::alloc::string::String,
}
/// / Health check request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthRequest {
    /// / Include detailed metrics
    #[prost(bool, tag = "1")]
    pub include_metrics: bool,
}
/// / Health check response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    /// / Overall health status
    #[prost(enumeration = "HealthStatus", tag = "1")]
    pub status: i32,
    /// / Component health details
    #[prost(message, repeated, tag = "2")]
    pub components: ::prost::alloc::vec::Vec<ComponentHealth>,
    /// / Metrics if requested
    #[prost(message, optional, tag = "3")]
    pub metrics: ::core::option::Option<BrokerMetrics>,
}
/// / Health of a component
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentHealth {
    /// / Component name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// / Health status
    #[prost(enumeration = "HealthStatus", tag = "2")]
    pub status: i32,
    /// / Additional details
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// / Broker metrics
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BrokerMetrics {
    /// / Total messages in outbox
    #[prost(int64, tag = "1")]
    pub outbox_pending: i64,
    /// / Total messages in inbox
    #[prost(int64, tag = "2")]
    pub inbox_pending: i64,
    /// / Messages published today
    #[prost(int64, tag = "3")]
    pub published_today: i64,
    /// / Messages processed today
    #[prost(int64, tag = "4")]
    pub processed_today: i64,
    /// / Current DLQ count
    #[prost(int64, tag = "5")]
    pub dlq_count: i64,
    /// / Active subscribers
    #[prost(int64, tag = "6")]
    pub active_subscribers: i64,
    /// / Kafka connection status
    #[prost(bool, tag = "7")]
    pub kafka_connected: bool,
    /// / Database connection status
    #[prost(bool, tag = "8")]
    pub database_connected: bool,
}
/// / Request to reprocess DLQ messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReprocessDlqRequest {
    /// / Specific message ID to reprocess
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Reprocess all messages from this topic
    #[prost(string, tag = "2")]
    pub topic: ::prost::alloc::string::String,
    /// / Reprocess all DLQ messages
    #[prost(bool, tag = "3")]
    pub all: bool,
    /// / Request metadata
    #[prost(message, optional, tag = "4")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response for reprocess request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReprocessDlqResponse {
    /// / Number of messages reprocessed
    #[prost(int32, tag = "1")]
    pub reprocessed_count: i32,
    /// / Number of failures
    #[prost(int32, tag = "2")]
    pub failure_count: i32,
    /// / Error details
    #[prost(string, repeated, tag = "3")]
    pub errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / Request to list DLQ messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDlqMessagesRequest {
    /// / Filter by original topic
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    /// / Maximum results
    #[prost(int32, tag = "2")]
    pub limit: i32,
    /// / Offset for pagination
    #[prost(int32, tag = "3")]
    pub offset: i32,
    /// / Request metadata
    #[prost(message, optional, tag = "4")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
/// / Response with DLQ messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDlqMessagesResponse {
    /// / DLQ messages
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<DlqMessageInfo>,
    /// / Total count matching filter
    #[prost(int32, tag = "2")]
    pub total_count: i32,
}
/// / Information about a DLQ message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DlqMessageInfo {
    /// / Message ID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Original topic
    #[prost(string, tag = "2")]
    pub original_topic: ::prost::alloc::string::String,
    /// / DLQ topic
    #[prost(string, tag = "3")]
    pub dlq_topic: ::prost::alloc::string::String,
    /// / Failure reason
    #[prost(string, tag = "4")]
    pub failure_reason: ::prost::alloc::string::String,
    /// / Number of retries attempted
    #[prost(int32, tag = "5")]
    pub retry_count: i32,
    /// / Timestamp when moved to DLQ
    #[prost(int64, tag = "6")]
    pub created_at: i64,
}
/// / Retry configuration for a message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetryConfig {
    /// / Maximum number of retry attempts
    #[prost(int32, tag = "1")]
    pub max_retries: i32,
    /// / Initial delay in milliseconds
    #[prost(int64, tag = "2")]
    pub initial_delay_ms: i64,
    /// / Multiplier for exponential backoff
    #[prost(double, tag = "3")]
    pub multiplier: f64,
    /// / Maximum delay in milliseconds
    #[prost(int64, tag = "4")]
    pub max_delay_ms: i64,
    /// / Whether to route to DLQ on failure
    #[prost(bool, tag = "5")]
    pub enable_dlq: bool,
    /// / Custom DLQ topic name
    #[prost(string, tag = "6")]
    pub dlq_topic: ::prost::alloc::string::String,
}
/// / Delivery configuration for subscriber
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeliveryConfig {
    /// / Timeout for gRPC calls in milliseconds
    #[prost(int64, tag = "1")]
    pub timeout_ms: i64,
    /// / Maximum concurrent deliveries
    #[prost(int32, tag = "2")]
    pub max_concurrent: i32,
    /// / Retry configuration for deliveries
    #[prost(message, optional, tag = "3")]
    pub retry_config: ::core::option::Option<RetryConfig>,
    /// / Whether to require acknowledgment
    #[prost(bool, tag = "4")]
    pub require_ack: bool,
}
/// / Request metadata for tracing and auditing
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestMetadata {
    /// / Correlation ID for request tracing
    #[prost(string, tag = "1")]
    pub correlation_id: ::prost::alloc::string::String,
    /// / ID of the calling service
    #[prost(string, tag = "2")]
    pub source_service: ::prost::alloc::string::String,
    /// / Timestamp of the request
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
    /// / Additional context
    #[prost(map = "string, string", tag = "4")]
    pub context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// / Request delivered to subscriber
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeliverRequest {
    /// / Unique message ID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// / Topic the message was received from
    #[prost(string, tag = "2")]
    pub topic: ::prost::alloc::string::String,
    /// / Message payload
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// / Message headers
    #[prost(message, repeated, tag = "4")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
    /// / Timestamp when message was produced
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
    /// / Event type
    #[prost(string, tag = "6")]
    pub event_type: ::prost::alloc::string::String,
    /// / Retry attempt number
    #[prost(int32, tag = "7")]
    pub retry_count: i32,
}
/// / Response from subscriber
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeliverResponse {
    /// / Whether delivery was successful
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// / Error message if failed
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    /// / Whether to retry delivery
    #[prost(bool, tag = "3")]
    pub retry: bool,
    /// / Suggested delay before retry in milliseconds
    #[prost(int64, tag = "4")]
    pub retry_delay_ms: i64,
}
/// / Message status enumeration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageStatus {
    Unspecified = 0,
    Pending = 1,
    Publishing = 2,
    Published = 3,
    Retrying = 4,
    Failed = 5,
    Dlq = 6,
    Received = 7,
    Processing = 8,
    Processed = 9,
    Delivered = 10,
}
impl MessageStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            MessageStatus::Unspecified => "MESSAGE_STATUS_UNSPECIFIED",
            MessageStatus::Pending => "MESSAGE_STATUS_PENDING",
            MessageStatus::Publishing => "MESSAGE_STATUS_PUBLISHING",
            MessageStatus::Published => "MESSAGE_STATUS_PUBLISHED",
            MessageStatus::Retrying => "MESSAGE_STATUS_RETRYING",
            MessageStatus::Failed => "MESSAGE_STATUS_FAILED",
            MessageStatus::Dlq => "MESSAGE_STATUS_DLQ",
            MessageStatus::Received => "MESSAGE_STATUS_RECEIVED",
            MessageStatus::Processing => "MESSAGE_STATUS_PROCESSING",
            MessageStatus::Processed => "MESSAGE_STATUS_PROCESSED",
            MessageStatus::Delivered => "MESSAGE_STATUS_DELIVERED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "MESSAGE_STATUS_PENDING" => Some(Self::Pending),
            "MESSAGE_STATUS_PUBLISHING" => Some(Self::Publishing),
            "MESSAGE_STATUS_PUBLISHED" => Some(Self::Published),
            "MESSAGE_STATUS_RETRYING" => Some(Self::Retrying),
            "MESSAGE_STATUS_FAILED" => Some(Self::Failed),
            "MESSAGE_STATUS_DLQ" => Some(Self::Dlq),
            "MESSAGE_STATUS_RECEIVED" => Some(Self::Received),
            "MESSAGE_STATUS_PROCESSING" => Some(Self::Processing),
            "MESSAGE_STATUS_PROCESSED" => Some(Self::Processed),
            "MESSAGE_STATUS_DELIVERED" => Some(Self::Delivered),
            _ => None,
        }
    }
}
/// / Delivery status for individual subscriber
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeliveryStatus {
    Unspecified = 0,
    Pending = 1,
    Delivering = 2,
    Delivered = 3,
    Retrying = 4,
    Failed = 5,
}
impl DeliveryStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DeliveryStatus::Unspecified => "DELIVERY_STATUS_UNSPECIFIED",
            DeliveryStatus::Pending => "DELIVERY_STATUS_PENDING",
            DeliveryStatus::Delivering => "DELIVERY_STATUS_DELIVERING",
            DeliveryStatus::Delivered => "DELIVERY_STATUS_DELIVERED",
            DeliveryStatus::Retrying => "DELIVERY_STATUS_RETRYING",
            DeliveryStatus::Failed => "DELIVERY_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DELIVERY_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "DELIVERY_STATUS_PENDING" => Some(Self::Pending),
            "DELIVERY_STATUS_DELIVERING" => Some(Self::Delivering),
            "DELIVERY_STATUS_DELIVERED" => Some(Self::Delivered),
            "DELIVERY_STATUS_RETRYING" => Some(Self::Retrying),
            "DELIVERY_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// / Subscription starting position
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SubscriptionPosition {
    Unspecified = 0,
    Latest = 1,
    Earliest = 2,
    Timestamp = 3,
}
impl SubscriptionPosition {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SubscriptionPosition::Unspecified => "SUBSCRIPTION_POSITION_UNSPECIFIED",
            SubscriptionPosition::Latest => "SUBSCRIPTION_POSITION_LATEST",
            SubscriptionPosition::Earliest => "SUBSCRIPTION_POSITION_EARLIEST",
            SubscriptionPosition::Timestamp => "SUBSCRIPTION_POSITION_TIMESTAMP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUBSCRIPTION_POSITION_UNSPECIFIED" => Some(Self::Unspecified),
            "SUBSCRIPTION_POSITION_LATEST" => Some(Self::Latest),
            "SUBSCRIPTION_POSITION_EARLIEST" => Some(Self::Earliest),
            "SUBSCRIPTION_POSITION_TIMESTAMP" => Some(Self::Timestamp),
            _ => None,
        }
    }
}
/// / Health status enumeration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HealthStatus {
    Unspecified = 0,
    Healthy = 1,
    Degraded = 2,
    Unhealthy = 3,
}
impl HealthStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            HealthStatus::Unspecified => "HEALTH_STATUS_UNSPECIFIED",
            HealthStatus::Healthy => "HEALTH_STATUS_HEALTHY",
            HealthStatus::Degraded => "HEALTH_STATUS_DEGRADED",
            HealthStatus::Unhealthy => "HEALTH_STATUS_UNHEALTHY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HEALTH_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "HEALTH_STATUS_HEALTHY" => Some(Self::Healthy),
            "HEALTH_STATUS_DEGRADED" => Some(Self::Degraded),
            "HEALTH_STATUS_UNHEALTHY" => Some(Self::Unhealthy),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod rs_broker_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Main service providing both producer and consumer operations
    #[derive(Debug, Clone)]
    pub struct RsBrokerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RsBrokerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RsBrokerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RsBrokerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            RsBrokerClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// / Publish a single message to the outbox for eventual Kafka delivery
        /// / Returns immediately with message ID, actual publishing is async
        pub async fn publish(
            &mut self,
            request: impl tonic::IntoRequest<super::PublishRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PublishResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/Publish",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("rsbroker.RsBroker", "Publish"));
            self.inner.unary(req, path, codec).await
        }
        /// / Publish multiple messages in a single batch
        /// / All messages are persisted atomically
        pub async fn publish_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::PublishBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PublishBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/PublishBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "PublishBatch"));
            self.inner.unary(req, path, codec).await
        }
        /// / Query the status of a previously published message
        pub async fn get_message_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMessageStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMessageStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/GetMessageStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "GetMessageStatus"));
            self.inner.unary(req, path, codec).await
        }
        /// / Cancel a pending message that has not yet been published
        pub async fn cancel_message(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelMessageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/CancelMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "CancelMessage"));
            self.inner.unary(req, path, codec).await
        }
        /// / Register a subscriber service to receive messages
        pub async fn register_subscriber(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterSubscriberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterSubscriberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/RegisterSubscriber",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "RegisterSubscriber"));
            self.inner.unary(req, path, codec).await
        }
        /// / Unregister a subscriber service
        pub async fn unregister_subscriber(
            &mut self,
            request: impl tonic::IntoRequest<super::UnregisterSubscriberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterSubscriberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/UnregisterSubscriber",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "UnregisterSubscriber"));
            self.inner.unary(req, path, codec).await
        }
        /// / Update subscriber configuration
        pub async fn update_subscriber(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateSubscriberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateSubscriberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/UpdateSubscriber",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "UpdateSubscriber"));
            self.inner.unary(req, path, codec).await
        }
        /// / List all registered subscribers
        pub async fn list_subscribers(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSubscribersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSubscribersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/ListSubscribers",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "ListSubscribers"));
            self.inner.unary(req, path, codec).await
        }
        /// / Stream for downstream services to receive messages in real-time
        /// / Alternative to push-based gRPC callbacks
        pub async fn subscribe_events(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::DeliverEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/SubscribeEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "SubscribeEvents"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// / Stream for upstream services to publish messages
        pub async fn stream_publish(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::PublishRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PublishResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/StreamPublish",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "StreamPublish"));
            self.inner.streaming(req, path, codec).await
        }
        /// / Get broker health and metrics
        pub async fn get_health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/GetHealth",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "GetHealth"));
            self.inner.unary(req, path, codec).await
        }
        /// / Reprocess a message from DLQ
        pub async fn reprocess_dlq(
            &mut self,
            request: impl tonic::IntoRequest<super::ReprocessDlqRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReprocessDlqResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/ReprocessDlq",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "ReprocessDlq"));
            self.inner.unary(req, path, codec).await
        }
        /// / List DLQ messages for monitoring
        pub async fn list_dlq_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::ListDlqMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDlqMessagesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBroker/ListDlqMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBroker", "ListDlqMessages"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod rs_broker_callback_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// / Service that downstream services must implement to receive messages
    #[derive(Debug, Clone)]
    pub struct RsBrokerCallbackClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RsBrokerCallbackClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RsBrokerCallbackClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RsBrokerCallbackClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            RsBrokerCallbackClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// / Called by rs-broker to deliver a message
        pub async fn deliver(
            &mut self,
            request: impl tonic::IntoRequest<super::DeliverRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeliverResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rsbroker.RsBrokerCallback/Deliver",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rsbroker.RsBrokerCallback", "Deliver"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod rs_broker_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RsBrokerServer.
    #[async_trait]
    pub trait RsBroker: Send + Sync + 'static {
        /// / Publish a single message to the outbox for eventual Kafka delivery
        /// / Returns immediately with message ID, actual publishing is async
        async fn publish(
            &self,
            request: tonic::Request<super::PublishRequest>,
        ) -> std::result::Result<tonic::Response<super::PublishResponse>, tonic::Status>;
        /// / Publish multiple messages in a single batch
        /// / All messages are persisted atomically
        async fn publish_batch(
            &self,
            request: tonic::Request<super::PublishBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PublishBatchResponse>,
            tonic::Status,
        >;
        /// / Query the status of a previously published message
        async fn get_message_status(
            &self,
            request: tonic::Request<super::GetMessageStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMessageStatusResponse>,
            tonic::Status,
        >;
        /// / Cancel a pending message that has not yet been published
        async fn cancel_message(
            &self,
            request: tonic::Request<super::CancelMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelMessageResponse>,
            tonic::Status,
        >;
        /// / Register a subscriber service to receive messages
        async fn register_subscriber(
            &self,
            request: tonic::Request<super::RegisterSubscriberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterSubscriberResponse>,
            tonic::Status,
        >;
        /// / Unregister a subscriber service
        async fn unregister_subscriber(
            &self,
            request: tonic::Request<super::UnregisterSubscriberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterSubscriberResponse>,
            tonic::Status,
        >;
        /// / Update subscriber configuration
        async fn update_subscriber(
            &self,
            request: tonic::Request<super::UpdateSubscriberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateSubscriberResponse>,
            tonic::Status,
        >;
        /// / List all registered subscribers
        async fn list_subscribers(
            &self,
            request: tonic::Request<super::ListSubscribersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSubscribersResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the SubscribeEvents method.
        type SubscribeEventsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::DeliverEvent, tonic::Status>,
            >
            + Send
            + 'static;
        /// / Stream for downstream services to receive messages in real-time
        /// / Alternative to push-based gRPC callbacks
        async fn subscribe_events(
            &self,
            request: tonic::Request<super::SubscribeEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SubscribeEventsStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamPublish method.
        type StreamPublishStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::PublishResponse, tonic::Status>,
            >
            + Send
            + 'static;
        /// / Stream for upstream services to publish messages
        async fn stream_publish(
            &self,
            request: tonic::Request<tonic::Streaming<super::PublishRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamPublishStream>,
            tonic::Status,
        >;
        /// / Get broker health and metrics
        async fn get_health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
        /// / Reprocess a message from DLQ
        async fn reprocess_dlq(
            &self,
            request: tonic::Request<super::ReprocessDlqRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReprocessDlqResponse>,
            tonic::Status,
        >;
        /// / List DLQ messages for monitoring
        async fn list_dlq_messages(
            &self,
            request: tonic::Request<super::ListDlqMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDlqMessagesResponse>,
            tonic::Status,
        >;
    }
    /// Main service providing both producer and consumer operations
    #[derive(Debug)]
    pub struct RsBrokerServer<T: RsBroker> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: RsBroker> RsBrokerServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RsBrokerServer<T>
    where
        T: RsBroker,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/rsbroker.RsBroker/Publish" => {
                    #[allow(non_camel_case_types)]
                    struct PublishSvc<T: RsBroker>(pub Arc<T>);
                    impl<T: RsBroker> tonic::server::UnaryService<super::PublishRequest>
                    for PublishSvc<T> {
                        type Response = super::PublishResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PublishRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::publish(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PublishSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/PublishBatch" => {
                    #[allow(non_camel_case_types)]
                    struct PublishBatchSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::PublishBatchRequest>
                    for PublishBatchSvc<T> {
                        type Response = super::PublishBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PublishBatchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::publish_batch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PublishBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/GetMessageStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetMessageStatusSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::GetMessageStatusRequest>
                    for GetMessageStatusSvc<T> {
                        type Response = super::GetMessageStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetMessageStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::get_message_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetMessageStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/CancelMessage" => {
                    #[allow(non_camel_case_types)]
                    struct CancelMessageSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::CancelMessageRequest>
                    for CancelMessageSvc<T> {
                        type Response = super::CancelMessageResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::cancel_message(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CancelMessageSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/RegisterSubscriber" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterSubscriberSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::RegisterSubscriberRequest>
                    for RegisterSubscriberSvc<T> {
                        type Response = super::RegisterSubscriberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterSubscriberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::register_subscriber(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = RegisterSubscriberSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/UnregisterSubscriber" => {
                    #[allow(non_camel_case_types)]
                    struct UnregisterSubscriberSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::UnregisterSubscriberRequest>
                    for UnregisterSubscriberSvc<T> {
                        type Response = super::UnregisterSubscriberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnregisterSubscriberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::unregister_subscriber(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = UnregisterSubscriberSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/UpdateSubscriber" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateSubscriberSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::UpdateSubscriberRequest>
                    for UpdateSubscriberSvc<T> {
                        type Response = super::UpdateSubscriberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateSubscriberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::update_subscriber(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = UpdateSubscriberSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/ListSubscribers" => {
                    #[allow(non_camel_case_types)]
                    struct ListSubscribersSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::ListSubscribersRequest>
                    for ListSubscribersSvc<T> {
                        type Response = super::ListSubscribersResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListSubscribersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::list_subscribers(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ListSubscribersSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/SubscribeEvents" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeEventsSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::ServerStreamingService<
                        super::SubscribeEventsRequest,
                    > for SubscribeEventsSvc<T> {
                        type Response = super::DeliverEvent;
                        type ResponseStream = T::SubscribeEventsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubscribeEventsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::subscribe_events(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SubscribeEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/StreamPublish" => {
                    #[allow(non_camel_case_types)]
                    struct StreamPublishSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::StreamingService<super::PublishRequest>
                    for StreamPublishSvc<T> {
                        type Response = super::PublishResponse;
                        type ResponseStream = T::StreamPublishStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::PublishRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::stream_publish(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamPublishSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/GetHealth" => {
                    #[allow(non_camel_case_types)]
                    struct GetHealthSvc<T: RsBroker>(pub Arc<T>);
                    impl<T: RsBroker> tonic::server::UnaryService<super::HealthRequest>
                    for GetHealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::get_health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetHealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/ReprocessDlq" => {
                    #[allow(non_camel_case_types)]
                    struct ReprocessDlqSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::ReprocessDlqRequest>
                    for ReprocessDlqSvc<T> {
                        type Response = super::ReprocessDlqResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReprocessDlqRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::reprocess_dlq(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ReprocessDlqSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rsbroker.RsBroker/ListDlqMessages" => {
                    #[allow(non_camel_case_types)]
                    struct ListDlqMessagesSvc<T: RsBroker>(pub Arc<T>);
                    impl<
                        T: RsBroker,
                    > tonic::server::UnaryService<super::ListDlqMessagesRequest>
                    for ListDlqMessagesSvc<T> {
                        type Response = super::ListDlqMessagesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListDlqMessagesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBroker>::list_dlq_messages(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ListDlqMessagesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: RsBroker> Clone for RsBrokerServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: RsBroker> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: RsBroker> tonic::server::NamedService for RsBrokerServer<T> {
        const NAME: &'static str = "rsbroker.RsBroker";
    }
}
/// Generated server implementations.
pub mod rs_broker_callback_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RsBrokerCallbackServer.
    #[async_trait]
    pub trait RsBrokerCallback: Send + Sync + 'static {
        /// / Called by rs-broker to deliver a message
        async fn deliver(
            &self,
            request: tonic::Request<super::DeliverRequest>,
        ) -> std::result::Result<tonic::Response<super::DeliverResponse>, tonic::Status>;
    }
    /// / Service that downstream services must implement to receive messages
    #[derive(Debug)]
    pub struct RsBrokerCallbackServer<T: RsBrokerCallback> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: RsBrokerCallback> RsBrokerCallbackServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RsBrokerCallbackServer<T>
    where
        T: RsBrokerCallback,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/rsbroker.RsBrokerCallback/Deliver" => {
                    #[allow(non_camel_case_types)]
                    struct DeliverSvc<T: RsBrokerCallback>(pub Arc<T>);
                    impl<
                        T: RsBrokerCallback,
                    > tonic::server::UnaryService<super::DeliverRequest>
                    for DeliverSvc<T> {
                        type Response = super::DeliverResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeliverRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RsBrokerCallback>::deliver(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = DeliverSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: RsBrokerCallback> Clone for RsBrokerCallbackServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: RsBrokerCallback> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: RsBrokerCallback> tonic::server::NamedService for RsBrokerCallbackServer<T> {
        const NAME: &'static str = "rsbroker.RsBrokerCallback";
    }
}
