//! REST handlers. Each handler parses an HTTP request into the same proto
//! request type the gRPC path uses, calls the shared `*_inner` method, and
//! maps the result/`Status` to JSON via [`crate::http::error`].

use std::sync::Arc;

use axum::extract::{Path, Query, State};
use axum::http::StatusCode;
use axum::Json;
use serde::Deserialize;

use rs_broker_proto::rsbroker::{
    CancelMessageRequest, GetMessageStatusRequest, HealthRequest, ListDlqMessagesRequest,
    ListSubscribersRequest, PublishBatchRequest, PublishRequest, RegisterSubscriberRequest,
    UnregisterSubscriberRequest, UpdateSubscriberRequest,
};

use crate::grpc::service::RsBrokerService;
use crate::http::dto;
use crate::http::error::ApiError;

/// Path params for `PATCH|DELETE /subscribers/{id}`.
#[derive(Debug, Deserialize)]
pub struct SubscriberIdPath {
    pub id: String,
}

/// POST /api/v1/publish
pub async fn publish(
    State(state): State<Arc<RsBrokerService>>,
    Json(body): Json<dto::PublishRequestDto>,
) -> Result<Json<dto::PublishResponseDto>, ApiError> {
    let proto_req: PublishRequest = body
        .into_proto()
        .map_err(|msg| ApiError::new(tonic::Status::invalid_argument(msg)))?;
    let resp = state.publish_inner(proto_req).await?;
    Ok(Json(resp.into()))
}

/// POST /api/v1/publish/batch
pub async fn publish_batch(
    State(state): State<Arc<RsBrokerService>>,
    Json(body): Json<dto::PublishBatchRequestDto>,
) -> Result<Json<dto::PublishBatchResponseDto>, ApiError> {
    let mut proto_reqs = Vec::with_capacity(body.messages.len());
    for message in body.messages {
        proto_reqs.push(
            message
                .into_proto()
                .map_err(|msg| ApiError::new(tonic::Status::invalid_argument(msg)))?,
        );
    }
    let resp = state
        .publish_batch_inner(PublishBatchRequest {
            messages: proto_reqs,
            metadata: body.metadata.map(Into::into),
        })
        .await?;
    Ok(Json(resp.into()))
}

/// GET /api/v1/messages/{id}
pub async fn get_message_status(
    State(state): State<Arc<RsBrokerService>>,
    Path(path): Path<SubscriberIdPath>,
) -> Result<Json<dto::GetMessageStatusResponseDto>, ApiError> {
    let resp = state
        .get_message_status_inner(GetMessageStatusRequest {
            message_id: path.id,
            metadata: None,
        })
        .await?;
    Ok(Json(resp.into()))
}

/// DELETE /api/v1/messages/{id}
pub async fn cancel_message(
    State(state): State<Arc<RsBrokerService>>,
    Path(path): Path<SubscriberIdPath>,
) -> Result<Json<dto::CancelMessageResponseDto>, ApiError> {
    let resp = state
        .cancel_message_inner(CancelMessageRequest {
            message_id: path.id,
            metadata: None,
        })
        .await?;
    Ok(Json(resp.into()))
}

/// POST /api/v1/subscribers
pub async fn register_subscriber(
    State(state): State<Arc<RsBrokerService>>,
    Json(body): Json<dto::RegisterSubscriberRequestDto>,
) -> Result<(StatusCode, Json<dto::SubscriberMutationResponseDto>), ApiError> {
    let resp = state
        .register_subscriber_inner(RegisterSubscriberRequest {
            subscriber_id: String::new(), // generated by the core registry
            service_name: body.service_name,
            grpc_endpoint: body.grpc_endpoint,
            topic_patterns: body.topic_patterns,
            delivery_config: body.delivery_config.map(Into::into),
            metadata: body.metadata.map(Into::into),
        })
        .await?;
    Ok((StatusCode::CREATED, Json(resp.into())))
}

/// GET /api/v1/subscribers?topic_filter=&active_only=
#[derive(Debug, Default, Deserialize)]
pub struct ListSubscribersQuery {
    pub topic_filter: Option<String>,
    pub active_only: Option<bool>,
}

pub async fn list_subscribers(
    State(state): State<Arc<RsBrokerService>>,
    Query(_query): Query<ListSubscribersQuery>,
) -> Result<Json<dto::ListSubscribersResponseDto>, ApiError> {
    let resp = state
        .list_subscribers_inner(ListSubscribersRequest {
            topic_filter: _query.topic_filter.unwrap_or_default(),
            active_only: _query.active_only.unwrap_or(false),
            metadata: None,
        })
        .await?;
    Ok(Json(resp.into()))
}

/// PATCH /api/v1/subscribers/{id}
pub async fn update_subscriber(
    State(state): State<Arc<RsBrokerService>>,
    Path(path): Path<SubscriberIdPath>,
    Json(body): Json<dto::UpdateSubscriberRequestDto>,
) -> Result<Json<dto::SubscriberMutationResponseDto>, ApiError> {
    let resp = state
        .update_subscriber_inner(UpdateSubscriberRequest {
            subscriber_id: path.id,
            grpc_endpoint: body.grpc_endpoint.unwrap_or_default(),
            topic_patterns: body.topic_patterns.unwrap_or_default(),
            active: body.active.unwrap_or(true),
            delivery_config: body.delivery_config.map(Into::into),
            metadata: body.metadata.map(Into::into),
        })
        .await?;
    Ok(Json(resp.into()))
}

/// DELETE /api/v1/subscribers/{id}
pub async fn unregister_subscriber(
    State(state): State<Arc<RsBrokerService>>,
    Path(path): Path<SubscriberIdPath>,
) -> Result<Json<dto::SubscriberMutationResponseDto>, ApiError> {
    let resp = state
        .unregister_subscriber_inner(UnregisterSubscriberRequest {
            subscriber_id: path.id,
            metadata: None,
        })
        .await?;
    Ok(Json(resp.into()))
}

/// GET /api/v1/health
pub async fn get_health(
    State(state): State<Arc<RsBrokerService>>,
) -> Result<Json<dto::HealthResponseDto>, ApiError> {
    let resp = state
        .get_health_inner(HealthRequest {
            include_metrics: true,
        })
        .await?;
    Ok(Json(resp.into()))
}

/// POST /api/v1/dlq/reprocess
pub async fn reprocess_dlq(
    State(state): State<Arc<RsBrokerService>>,
    Json(body): Json<dto::ReprocessDlqRequestDto>,
) -> Result<Json<dto::ReprocessDlqResponseDto>, ApiError> {
    let resp = state.reprocess_dlq_inner(body.into_proto()).await?;
    Ok(Json(resp.into()))
}

/// GET /api/v1/dlq?topic=&limit=&offset=
pub async fn list_dlq_messages(
    State(state): State<Arc<RsBrokerService>>,
    Query(query): Query<dto::ListDlqQuery>,
) -> Result<Json<dto::ListDlqMessagesResponseDto>, ApiError> {
    let resp = state
        .list_dlq_messages_inner(ListDlqMessagesRequest {
            topic: query.topic.unwrap_or_default(),
            limit: query.limit.unwrap_or(50),
            offset: query.offset.unwrap_or(0),
            metadata: None,
        })
        .await?;
    Ok(Json(resp.into()))
}
